# Generated by Django 3.1.4 on 2021-01-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('jobTitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=30)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.project')),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.skill')),
            ],
        ),
    ]
