# Generated by Django 3.1.4 on 2021-01-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='jobTitle',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='profileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectTitle',
            new_name='project_title',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='categoryId',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skillName',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='projectId',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='skillId',
            new_name='skill_id',
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.profile')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_folio_app.skill')),
            ],
        ),
    ]
