# Generated by Django 3.1.4 on 2021-01-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio_app', '0002_auto_20210105_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileskill',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profileskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='category_id',
            new_name='category',
        ),
    ]
