# Generated by Django 3.1.4 on 2021-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio_app', '0003_auto_20210111_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_svg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_svg',
            field=models.TextField(null=True),
        ),
    ]
