# Generated by Django 3.1.4 on 2021-01-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio_app', '0004_auto_20210116_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_name',
            field=models.BooleanField(default=True),
        ),
    ]
