# Generated by Django 3.1.4 on 2021-01-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio_app', '0006_auto_20210119_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo_svg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_svg',
            field=models.TextField(null=True),
        ),
    ]
